port: 4001

# Site settings
title: Demo Blog
subtitle: A launchpad project
description: >-
  This demo blog was built to accompany my own blog post about creating a fully
  functional portfolio website and blogging platform based on GitHub Pages,
  complete with a CI/CD solution using Travis CI, minified HTML via
  compress_html and a custom domain (if so desired).

# Personal Info
owner: Lucas Vienna
email: dev@lucasvienna.dev
url: https://avyiel.github.io # the custom domain you configure ealier
baseurl:  # what comes after the '.io'
repository: Avyiel/lucasvienna.dev # only the path part of the repository URL

# Blogging Defaults
author: Lucas Vienna

# Build settings
markdown: kramdown # this is the default, you can omit this line if desired
highlighter: rouge # this is the default, you can omit this line if desired
compress_html:
  blanklines: true
  comments: ["<!-- ", " -->"]
  ignore:
    envs: [development] # don't compress during development