# Website
title: Vicropht
subtitle: Karlsruhe University of Applied Sciences
description: >- # this means to ignore newlines until "baseurl:"
  My personal blog and portfolio for sharing my ideas and projects with the internet
baseurl: ""
url: "https://vicropht.com"

# About me
owner: Victor Brincas Sinkunas
email: vicropht@protonmail.com
repository: Vicropht/vicropht.com
author: Victor Brincas Sinkunas

# Social
twitter:
  handle: CristophVictor
  url: https://twitter.com/CristophVictor
github:
  username: Vicropht
  url: https://github.com/Vicropht
linkedin:
  username: vicropht
  url: https://linkedin.com/in/vicropht

  # Build settings
  include: ['_pages']
markdown: kramdown
highlighter: rouge
compress_html:
  blanklines: true
  comments: ["<!-- ", " -->"]
  ignore:
    envs: [development] # don't compress during development
