port: 4001

# Site settings
title: (Under Development!) Vicropht
subtitle: Karlsruhe University of Applied Sciences | International IT Business
description: >-
  My personal portfolio and blog to share my ideas and projects for the internet.

# Personal Info
owner: Victor Brincas Sinkunas
email: vicropht@protonmail.com
url: https://vicropht.com # the custom domain you configure ealier
baseurl:  # what comes after the '.io'
repository: Vicropht/vicropht.com # only the path part of the repository URL
author: Victor Cristoph Brincas Sinkunas

# Social media
twitter:
  handle: CristophVictor
  url: https://twitter.com/CristophVictor
github:
  username: Vicropht
  url: https://github.com/Vicropht
linkedin:
  username: vicropht
  url: https://linkedin.com/in/vicropht

# Display settings
show_github: false
show_downloads: false

# Build settings
markdown: kramdown # this is the default, you can omit this line if desired
highlighter: rouge # this is the default, you can omit this line if desired
compress_html:
  blanklines: true
  comments: ["<!-- ", " -->"]
  ignore:
    envs: [development] # don't compress during development